version: "3"
services:

  teslalogger:
    build: docker/teslalogger/.
    restart: always
    volumes:
      - ./TeslaLogger/www:/var/www/html
      - ./TeslaLogger/bin:/etc/teslalogger
      - ./TeslaLogger/GrafanaDashboards/:/var/lib/grafana/dashboards/
      - ./TeslaLogger/GrafanaPlugins/:/var/lib/grafana/plugins
      - ./docker/teslalogger/Dockerfile:/tmp/teslalogger-DOCKER
      - teslalogger-tmp:/tmp/
    depends_on:
      - database
    environment:
      - TZ=Europe/Berlin
    networks:
      default:
      nginx:
        aliases:
          - teslalogger_api

  database:
    image: mariadb:10.4.7
    restart: always
    env_file:
      - .env
    volumes:
      - ./TeslaLogger/sqlschema.sql:/docker-entrypoint-initdb.d/sqlschema.sql
      - ./TeslaLogger/mysql:/var/lib/mysql
    environment:
      - TZ=Europe/Berlin
    networks:
      - default

  grafana:
    image: grafana/grafana:10.0.1
    restart: always
    environment:
      #- GF_SECURITY_ADMIN_PASSWORD=teslalogger
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=natel-discrete-panel,pr0ps-trackmap-panel,teslalogger-timeline-panel
      - TZ=Europe/Berlin
    volumes:
      - ./TeslaLogger/bin:/etc/teslalogger
      - ./TeslaLogger/GrafanaDashboards/:/var/lib/grafana/dashboards/
      - ./TeslaLogger/GrafanaPlugins/:/var/lib/grafana/plugins
      - ./TeslaLogger/GrafanaDB:/var/lib/grafana/
      - ./TeslaLogger/GrafanaConfig/datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yml
      - ./TeslaLogger/GrafanaConfig/sample.yaml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./TeslaLogger/GrafanaConfig/grafana.ini:/etc/grafana/grafana.ini
    depends_on:
      - database
    networks:
      default:
        aliases:
          - teslalogger_grafana
      nginx:
        aliases:
          - teslalogger_grafana

  webserver:
    build: docker/webserver/.
    restart: always
    volumes:
      - ./docker/webserver/php.ini:/usr/local/etc/php/php.ini
      - ./TeslaLogger/www:/var/www/html
      - ./TeslaLogger/bin:/etc/teslalogger
      - ./docker/teslalogger/Dockerfile:/tmp/teslalogger-DOCKER
      - ./TeslaLogger/GrafanaConfig/datasource.yaml:/tmp/datasource-DOCKER
      - teslalogger-tmp:/tmp/
    environment:
      - TZ=Europe/Berlin
    networks:
      default:
      nginx:
        aliases:
          - teslalogger_webserver

volumes:
    teslalogger-tmp:

networks:
  default:

  nginx:
    name: nginx_network
    external: true
